### ISSUE TITLE
Buffer data in RP calls exhausting gitlab log limit 

### ISSUE THREAD

**Issue by chirag-fynd** [reportportal/agent-js-playwright#103]
While running playwright suites on CICD, the gitlab log limit is exhausted because of buffer request data in calls to Report Portal

> Error: Request body larger than maxBodyLength limit
> URL: https://reportportal.company.engineering/api/v1/company/log
> method: POST
> Request data: {"type":"Buffer","data":[45,45,56,51,57,56,53,51,50,53,51........

Gitlab console 

> Job's log exceeded limit of 10240000 bytes.
> Job execution will continue but no more output will be collected.

<img width="1497" alt="Screenshot 2023-06-01 at 1 31 58 PM" src="https://github.com/reportportal/agent-js-playwright/assets/107979613/aca239b3-5dfd-4c2a-a603-f22c54edb92d">

**Comment by AmsterGet** [comment]
Hello @chirag-fynd !
The issue was related to [client-javascript](https://github.com/reportportal/client-javascript), fixed in [client-javascript@v5.0.11](https://github.com/reportportal/client-javascript/releases/tag/v5.0.11).
Please reinstall the `agent-js-playwright` to get the latest version of `client-javascript`.
