### ISSUE TITLE
[Security Issue] Upgrade the axios version to solve the security issue  'follow-redirects' Proxy-Authorization header kept across hosts #1'

### ISSUE THREAD

**Issue by tamtmnguyen-kms** [reportportal/agent-js-playwright#143]
Hi team,
My Github GitHub found 1 vulnerability on my repo rated to **follow-redirects' Proxy-Authorization header kept across hosts**
My setup:  "@playwright/test": "^1.41.2", "@reportportal/agent-js-playwright": "^5.1.7".
Please take a look. Thanks!

<img width="1017" alt="image" src="https://github.com/reportportal/agent-js-playwright/assets/154446575/99f32734-8596-4da9-a84b-da06598096fc">

<img width="1017" alt="image" src="https://github.com/reportportal/agent-js-playwright/assets/154446575/8c6eb304-f72b-4abe-aa16-74f00aa5056f">

**Comment by AmsterGet** [comment]
Hi @tamtmnguyen-kms !
Thank you for pointing this out.
We are aware of this vulnerable dependency, it is part of our client-javascript.
Since it is medium severity and we don't use the `Proxy-Authorisation` header directly, we will fix it within a few weeks.
In case you are affected, the `follow-redirects` dependency can be safely updated in your codebase until we publish a fix.
Thanks!

**Comment by AmsterGet** [comment]
Hi @tamtmnguyen-kms !
A new version of the package [5.1.8](https://github.com/reportportal/agent-js-playwright/releases/tag/v5.1.8) with the corresponding fixes is now available.
Please check it out.
