### ISSUE TITLE
Get ID of a Report portal launch

### ISSUE THREAD

**Issue by lucas-delafuente-deel** [reportportal/agent-js-playwright#146]
Hi team,
I read this issue https://github.com/reportportal/agent-js-playwright/issues/125, I noticed that now the report portal link is in the terminal as 'ReportPortal Launch Link:', but I would like to know If I can get the Launch ID as I need this ID to create the URL because I want to post it in a Slack message.

Thank you!

**Comment by AmsterGet** [comment]
Hi @lucas-delafuente-deel !
Please use the option [launchUuidPrint](https://github.com/reportportal/agent-js-playwright#:~:text=for%20more%20details.-,launchUuidPrint,-Optional) together with specifying its output via [launchUuidPrintOutput](https://github.com/reportportal/agent-js-playwright#:~:text=current%20launch%20UUID.-,launchUuidPrintOutput,-Optional).

Hope this helps!

**Comment by lucas-delafuente-deel** [comment]
Thanks for the answer @AmsterGet , I'm not sure if I understand:
This is my config:
const RPconfig = {
  apiKey: process.env.REPORT_PORTAL_API_KEY,
  endpoint: process.env.REPORT_PORTAL_ENDPOINT,
  project: process.env.REPORT_PORTAL_PROJECT,
  launch: process.env.REPORT_PORTAL_PROJECT_TITLE,
  includeTestSteps: true,
  attributes: [
    {
      key: 'Owner',
      value: process.env.GITHUB_USER_NAME,
    },
    {
      key: 'Environment',
      value: `${process.env.BASE_URL} and ${process.env.ADMIN_URL}`,
    },
    {
      key: 'Pipeline ID',
      value: process.env.GITHUB_PIPELINE_ID,
    },
  ],
  description: process.env.GITHUB_COMMIT_BRANCH,
  debug: false,
  skippedIssue: false,
  mode: 'DEFAULT',
  **launchUuidPrint: true,
  launchUuidPrintOutput: 'ENVIRONMENT',**
};

So, to know the launchUuid in other part of the code, I should use: process.env.RP_LAUNCH_UUID, right?
I tried that way, but the value is undefined.

**Comment by lucas-delafuente-deel** [comment]
Any idea about it 🙏 ?

**Comment by AmsterGet** [comment]
Hi @lucas-delafuente-deel !
> So, to know the launchUuid in other part of the code, I should use: `process.env.RP_LAUNCH_UUID`, right?
I tried that way, but the value is undefined.

Where are you trying to access the `RP_LAUNCH_UUUID`, inside the tests or somewhere else?

In the case of accessing it inside tests, it looks like Playwright doesn't propagate the environment information set by the reporter into the main test execution process, so we need to put extra effort into making it safely accessible from tests.

In the meantime, try using `launchUuidPrintOutput: 'FILE'`, a file named with `uuid` will be created right after a successful launch start.

**Comment by lucas-delafuente-deel** [comment]
I'm trying to access to RP_LAUNCH_UUUID at the end of the execution to make the link in the Slack message.
Right now the slack message contain the link to the Launches, but the idea is the link is that of the specific execution, so that when you click it redirects you to the corresponding execution and not to the launches page. 

 I would like to have this as a link: https://reportportal.com/ui/#playwright/launches/all/4064, but the Launch UUId looks more like: UUID: 4e074212-a080-4640-b432-efa10dc4as12, so, Am I right with this?

I tried with 'FILE' but I don't see any new file after execution :(. 

Image of the execution: ✅ 
<img width="1023" alt="Screenshot 2024-05-16 at 10 06 23 AM" src="https://github.com/reportportal/agent-js-playwright/assets/153518950/67c99f3a-f86c-42b8-9ac6-537c8e1d5864">

**Comment by AmsterGet** [comment]
> I'm trying to access to RP_LAUNCH_UUID at the end of the execution to make the link in the Slack message.

Do you mean trying to do it in the scope of [globalTeardown](https://playwright.dev/docs/test-global-setup-teardown#option-2-configure-globalsetup-and-globalteardown)?

> I would like to have this as a link: https://reportportal.com/ui/#playwright/launches/all/4064, but the Launch UUId looks more like: UUID: 4e074212-a080-4640-b432-efa10dc4as12, so, Am I right with this?

The RP UI supports both the `UUID` and the numeric `id` formats, so the links `https://reportportal.com/ui/#playwright/launches/all/4064` and `https://reportportal.com/ui/#playwright/launches/all/4e074212-a080-4640-b432-efa10dc4as12` will produce the same result. So you can safely use the `UUID` instead of `id` for building URLs.

> I tried with 'FILE' but I don't see any new file after execution :(.

I just double-checked this myself, and it seems to work as expected with `"@reportportportportal/agent-js-playwright": "5.1.8"`.
File created (see the screenshot below).

![image](https://github.com/reportportal/agent-js-playwright/assets/31861805/d454e93e-8d66-49e3-b621-6502f2855984)

Could you please double-check this with agent version `5.1.8`?

**Comment by lucas-delafuente-deel** [comment]
Thank you for the answer.
I tried different things.

First of all, I was using 5.1.7, I updated to 5.1.8 and I see the file now.
The issue with this is that the package that we are using to send the message to Slack is configured in the reports array of Playwright and this takes the values at the beginning of the execution, and in that array is the URL to send to Slack, but in that moment we don't have the UUID, this is generated after that, so, I can't make the correct URL :(

I think there isn't a solution for my idea with the current implementation.

**Comment by AmsterGet** [comment]
Hi @lucas-delafuente-deel !

I don't see a solution that can be done on the agent side for your specific use case.

But I can suggest some options for the case you describe:

1. Since the launch UUID from ReportPortal can only be retrieved asynchronously as it is requested from the server over the network, a delay will occur anyway.
Therefore, you can configure another reporter to wait for the UUID file to be available.
This is not ideal and should be limited by the number of retries and timeout, but may help.

2. You can add a launch attribute that should be unique for each launch, and then use the same attribute value in the reporter to create a link to the launches page with the filtered launches.

Link should look like this: `https://reportportal.com/ui/#playwright/launches/all?launchesParams=filter.has.compositeAttribute%26${attribute}`, where attribute is f.e. `agent%3Aplaywright`.
Special characters are encoded here because the UI uses nested URL parameters.

Clicking on the link will bring up a launches page with a single target launch.

![image](https://github.com/reportportal/agent-js-playwright/assets/31861805/b1924b89-69eb-4e42-b11e-1fd9ad45a291)

3. You could also try doing an attribute-based startup search via a separate API call to RP, but there's no guarantee it will be created at that point in the request, so that would also result in some polling.

Let me know what you think.

**Comment by AmsterGet** [comment]
Hello @lucas-delafuente-deel !
Were you able to check my suggestions?
Any thoughts on this?
